name: run write-good on *.md

on: push

jobs:
  run-write-good:
    runs-on: ubuntu-latest
    steps:
      - name: run-write-good
        run: |
          npm install -g write-good 
          write-good *.md
          
